### ISSUE TITLE
Add geometry tool to FarmParcel web UI view

### ISSUE THREAD

**Issue by arruda** [openagri-eu/farmcalendar#35]
Add some sort of web ui tools to allow the user the specify the geometry data of the farmparcel 

Agstack uses: https://smeijer.github.io/leaflet-geosearch/

https://openlayers.org/en/latest/examples/wkt.html
https://openlayers.org/en/latest/examples/draw-features.html

**Comment by pranavnbapat** [comment]
We can use Leaflet.js, as it's lightweight and powerful. I have never used it, though. I will have to do some R&D on it.

**Comment by arruda** [comment]
I liked leaflet, but the issue that I saw with it is that it doesn't seem to have support for the WKT format, that is what I saw on the example from nikos, and is also the geometry format used by LF in their asset manager, so I think I'll go back to the openlayers then.

**Comment by arruda** [comment]
Ended up using the OpenLayers because of the WKT format, so now we should have a easy integration with the expected OCSM and the LF asset manager. 
The only thing that is an "issue" (but not really) is that the map feature will need to be disabled in "offline" mode (this is an issue for both OpenLayers or Leaflet, since they depend on an online map visualization).
The alternative is to have a local server that provides the "tiles" of the maps, but I don't think that is a viable solution for a resource constrainde devices environment. So we ca simply limit the map to online mode, (like we mention on the project description when we say that the offline features will be limited).
